tap "atlassian/homebrew-acli"
tap "dsully/tap"
#tap "nikitabobko/tap"
tap "darrylmorley/whatcable"


brew "dsully/tap/macos-defaults"
brew "atlassian/homebrew-acli/acli"
brew "bash"
brew "bat"
brew "curl"
brew "fd"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "gnutls"
brew "go"
brew "golangci-lint"
brew "gpgme"
brew "grep"
brew "hey"
brew "htop"
brew "jq"
brew "luajit"
brew "neovim"
brew "node"
brew "pam-reattach"
brew "pandoc"
brew "pinentry"
brew "pinentry-mac"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "sevenzip"
brew "stow"
brew "stylua"
brew "tmux"
brew "tree"
brew "tree-sitter-cli"
brew "uv"
brew "watch"
brew "wget"
brew "wordnet"
brew "yarn"
brew "yq"

cask "font-roboto-mono-nerd-font"
cask "google-drive"
cask "iterm2"
cask "stats"
cask "meld"
# cask "visual-studio-code"
cask "dbeaver-community"
# cask "cursor"
cask "darrylmorley/whatcable/whatcable"

# cask "nikitabobko/tap/aerospace"

# cask "google-chrome"
# cask "slack"
# cask "basictex"

# vim: set ft=ruby:
